[directories]
astetcdir => /etc/asterisk
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => /var/lib/asterisk
astdbdir => /var/lib/asterisk
astkeydir => /var/lib/asterisk
astdatadir => /var/lib/asterisk
astagidir => /var/lib/asterisk/agi-bin
astspooldir => /var/spool/asterisk
astrundir => /var/run/asterisk
astlogdir => /var/log/asterisk

[options]
verbose = 3
debug = 3
dumpcore = yes
dontwarn = yes
hideconnect = yes
languageprefix = yes
maxcalls = 100
maxload = 0.9
maxfiles = 1000

[compat]
pbx_realtime=1
res_agi=1
res_crypto=1
app_set=1
app_dial=1
app_macro=1
