[general]
context=default
allowoverlap=no
bindport=5060
bindaddr=0.0.0.0
srvlookup=yes
tcpenable=yes
tcpbindaddr=0.0.0.0
transport=udp

[shadowpbx]
type=friend
host=shadowpbx-drachtio
port=5060
context=sip-trunk
dtmfmode=rfc2833
canreinvite=no
insecure=port,invite
qualify=yes
nat=yes
disallow=all
allow=ulaw
allow=alaw
